### ISSUE TITLE
Logstash 5.x Compatibility

### ISSUE THREAD

**Issue by krisko** [logstash-plugins/logstash-input-jmx#26]
Hi,
I'm getting an error message when trying to install this plugin for rc1 release.
- Version: 5.0.0-rc1
- Steps to Reproduce: ./bin/logstash-plugin install --no-verify logstash-input-jmx
- Error Msg:
  ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core-plugin-api":
  In snapshot (Gemfile.lock):
    logstash-core-plugin-api (= 2.1.16)
  ...

**Comment by nothau** [comment]
@I tried to force it in by updating the version restriction in logstash-input-jmx.gemspec

From:
-   s.add_runtime_dependency "logstash-core-plugin-api", ">= 1.60", "<= 2.9.9"

To:
-   s.add_runtime_dependency "logstash-core-plugin-api", ">= 1.60", "<= 5.0.0"

But ran into an error when actually parsing through the jmx data it recieved (from cassandra 3.0):
`undefined method`event' for #LogStash::Inputs::Jmx:0x4128d182`

> [2016-10-28T20:39:22,744][WARN ][logstash.inputs.jmx      ] Failed retrieving metrics for attribute object_name on object java.nio:type=BufferPool,name=mapped
> [2016-10-28T20:39:22,744][WARN ][logstash.inputs.jmx      ] undefined method `event' for #LogStash::Inputs::Jmx:0x4128d182

**Comment by untergeek** [comment]
I'm guessing it's because these lines should read `event.set(` and not `event(`

https://github.com/logstash-plugins/logstash-input-jmx/blob/master/lib/logstash/inputs/jmx.rb#L175-L177

Since event.set is a method, but not event.

**Comment by nothau** [comment]
That was it, working now.

**Comment by talevy** [comment]
fixed by latest commit and published as version `3.0.0`

**Comment by boernd** [comment]
@talevy I think you forgot to apply the fix mentioned above? Issue still present in 3.0.0

**Comment by krizsan** [comment]
As of writing, in a Docker container with Logstash 5.0.1-1, I get a lot of this log output:
```
WARN  logstash.inputs.jmx - undefined method `event' for #<LogStash::Inputs::Jmx:0x7d39170a>
```
As recommended, I install with:
```
logstash-plugin install --no-verify logstash-input-jmx
```
Am I doing something wrong?

**Comment by mrosterm** [comment]
I think @boernd might be right. I'm also having issues with 3.0.0 being broken. @talevy please release a new build 😄

**Comment by diedirk** [comment]
+1 Will be great to get a new release

**Comment by ghost** [comment]
+1

**Comment by talevy** [comment]
@diedirk @krizsan @mrosterm @boernd, published version `3.0.1` with #27, thanks!
